---
# ===============================================
# ANSIBLE CONFIGURATION
# ===============================================
ansible_host: chongus
ansible_user: root

# ===============================================
# HOST CONFIGURATION
# ===============================================
hostname: chongus
domain: local
fqdn: "{{ hostname }}.{{ domain }}"
cpu_type: intel


# ===============================================
# NESTED VIRTUALIZATION CONFIGURATION
# ===============================================
proxmox_nested_virt_cpu_type: "{{ cpu_type }}"

# ===============================================
# GPU PASSTHROUGH CONFIGURATION
# ===============================================
proxmox_pci_passthrough_boot_type: systemd
proxmox_pci_passthrough_cpu_type: "{{ cpu_type }}"
proxmox_pci_passthrough_gpu_ids: 10de:1e84,10de:10f8,10de:1ad8,10de:1ad9,10de:1c81,10de:0fb9
proxmox_pci_passthrough_extra_cmdline: pcie_acs_override=downstream pcie_acs_override=multifunction nofb nomodeset video=vesafb:off video=efifb:off video=simplefb:off initcall_blacklist=sysfb_init vga=off
