---
- name: Install and Configure Automaton
  hosts: automaton
  become: true

  pre_tasks:
    - name: Update and Upgrade System
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Install Utility Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "{{ apt_utility_state }}"
      loop: "{{ apt_utility_packages }}"

  roles:
    # Installed required packages for local development
    - role: mirceanton.terraform
    - role: mirceanton.packer
    - role: mirceanton.ansible

    # Deploy Docker & Docker Swarm for Service Hosting
    - role: mirceanton.docker
    - role: mirceanton.docker_swarm

    # Deploy Services
    - role: mirceanton.docker_stack_deploy
      vars:
        docker_stack_deploy_name: "{{ traefik_stack_name }}"
        docker_stack_deploy_root_dir_path: "{{ traefik_stack_data_dir_path }}"
        docker_stack_deploy_root_dir_mode: "{{ traefik_stack_data_dir_mode }}"
        docker_stack_deploy_additional_dirs: "{{ traefik_stack_additional_dirs }}"
        docker_stack_deploy_copy_files: []
        docker_stack_deploy_template_files: "{{ traefik_stack_template_files }}"
    - role: mirceanton.docker_stack_deploy
      vars:
        docker_stack_deploy_name: "{{ portainer_stack_name }}"
        docker_stack_deploy_root_dir_path: "{{ portainer_stack_data_dir_path }}"
        docker_stack_deploy_root_dir_mode: "{{ portainer_stack_data_dir_mode }}"
        docker_stack_deploy_additional_dirs: "{{ portainer_stack_additional_dirs }}"
        docker_stack_deploy_copy_files: []
        docker_stack_deploy_template_files: "{{ portainer_stack_template_files }}"
    - role: mirceanton.docker_stack_deploy
      vars:
        docker_stack_deploy_name: "{{ vault_stack_name }}"
        docker_stack_deploy_root_dir_path: "{{ vault_stack_data_dir_path }}"
        docker_stack_deploy_root_dir_mode: "{{ vault_stack_data_dir_mode }}"
        docker_stack_deploy_additional_dirs: "{{ vault_stack_additional_dirs }}"
        docker_stack_deploy_copy_files: []
        docker_stack_deploy_template_files: "{{ vault_stack_template_files }}"

  tasks: []
