---
- name: Install and Configure Automaton
  hosts: automaton
  become: true

  pre_tasks:
    - name: Update and Upgrade System
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Install Utility Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "{{ apt_utility_state }}"
      loop: "{{ apt_utility_packages }}"

  roles:
    - role: mirceanton.terraform
    - role: mirceanton.packer
    - role: mirceanton.docker
      vars:
        docker_users: [ mike ]
    - role: mirceanton.ansible
      vars:
        pip_additional: [ lxml, docker, jsondiff ]

  tasks:
    - name: Initialize The Docker Swarm
      community.docker.docker_swarm:
        state: "{{ docker_swarm_state }}"
        advertise_addr: "{{ docker_swarm_iface }}"
