---
- name: Install and Configure Automaton
  hosts: automaton
  become: true

  pre_tasks:
    - name: "automaton: Update and Upgrade System"
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: "automaton: Install Utility Packages"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "{{ apt_utility_state }}"
      loop: "{{ apt_utility_packages }}"

  roles:
    - role: mirceanton.terraform
    - role: mirceanton.packer
    - role: mirceanton.docker
      vars:
        docker_users: [ mike ]
    - role: mirceanton.ansible
      vars:
        ansible_pip_additional: [ lxml, docker, jsondiff ]

  tasks:
    - name: "automaton: Initialize The Docker Swarm"
      community.docker.docker_swarm:
        state: "{{ docker_swarm_state }}"
        advertise_addr: "{{ docker_swarm_iface }}"

    - import_tasks: tasks/deploy-traefik.yml
    - import_tasks: tasks/deploy-portainer.yml
    - import_tasks: tasks/deploy-jenkins.yml
    - import_tasks: tasks/deploy-vault.yml
    - import_tasks: tasks/deploy-minio.yml