---
- name: Set System Location
  community.ciscosmb.command:
    commands: snmp-server location "Top of rack"
  register: __cmd__
- debug:
    var: __cmd__.stdout

- name: Set System Contact
  community.ciscosmb.command:
    commands: snmp-server contact "Mircea Anton"
  register: __cmd__
- debug:
    var: __cmd__.stdout

- name: Set Hostname
  community.ciscosmb.command:
    commands: hostname coresw
  register: __cmd__
- debug:
    var: __cmd__.stdout

- name: Set Login Banner
  community.ciscosmb.command:
    commands: banner login //Login banner!//
  register: __cmd__
- debug:
    var: __cmd__.stdout

- name: Set Welcome Banner
  community.ciscosmb.command:
    commands: banner exec //Welcome banner!//
  register: __cmd__
- debug:
    var: __cmd__.stdout
