---
- name: Deploy Automaton Services
  hosts: automaton
  become: true

  pre_tasks:
    - name: Initialize The Docker Swarm
      community.docker.docker_swarm:
        state: "{{ docker_swarm_state }}"
        advertise_addr: "{{ docker_swarm_iface }}"

    - name: Create the Overlay Network
      community.docker.docker_network:
        name: "{{ docker_proxy_network }}"
        scope: swarm
        driver: overlay

- import_playbook: traefik/main.yml
- import_playbook: portainer/main.yml
- import_playbook: minio/main.yml
- import_playbook: vault/main.yml
- import_playbook: jenkins/main.yml
- import_playbook: gitlab/main.yml
- import_playbook: homer/main.yml
