---
- name: Restore Automaton
  hosts: automaton
  gather_facts: false
  become: true

  tasks:
    - name: Restore Data Directory
      ansible.posix.synchronize:
        src: "{{ backup_dir }}/{{ item }}"
        dest: "{{ service_data_dir }}"
      loop:
        - "{{ traefik_stack_name }}"
        - "{{ portainer_stack_name }}"
        - "{{ vault_stack_name }}"
        - "{{ minio_stack_name }}"
        - "{{ jenkins_stack_name }}"
        - "{{ gitlab_stack_name }}"
        - "{{ homer_stack_name }}"
