---
# ===============================================
# TRUENAS PACKER PROJECT
# ===============================================
truenas_pkr_repo: https://github.com/mirceanton/packer-proxmox_truenas
truenas_pkr_tag: v1.0.0
truenas_pkr_dest: ../../utils/packer/truenas

# ===============================================
# TRUENAS PACKER CONFIGURATION
# ===============================================
# [Required] The URL to download the TrueNAS ISO
truenas_iso_url: https://download.freenas.org/13.0/STABLE/U3.1/x64/TrueNAS-13.0-U3.1.iso

# [Required] The name for the TrueNAS ISO file
truenas_iso_name: TrueNAS-13.0-U3.1.iso

# [Required] The path to the ISO file, including the storage device
truenas_tpl_iso: local:iso/{{ truenas_iso_name }}

# [Required] The name of the node on which to deploy the VM
truenas_tpl_node: '{{ ansible_hostname }}'

# [Optional] The ID of the VM template
truenas_tpl_id: 1100

# [Optional] The name of the VM template
truenas_tpl_name: TrueNAS-tpl

# [Required] The password to set for the root user
truenas_tpl_root_pass: test123

# [Required] List of network devices
truenas_tpl_networks:
  - bridge: vmbr0 # [Required] The name of the network bridge to attach to. (vmbr0, vmbr1 etc)

# [Required] List of disks to assign to the VM
truenas_tpl_disks:
  - size: 16G                     # [Required] The name of the storage pool on which to store the disk
    storage_pool: local-zfs       # [Required] The name of the storage pool on which to store the disk
    storage_pool_type: zfspool    # [Required] The type of the storage pool on which to store the disk
