---
- name: Configure Automaton
  hosts: automaton
  become: true

  pre_tasks:
    - name: Update and Upgrade System
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Install Utility Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "{{ apt_utility_state }}"
      loop: "{{ apt_utility_packages }}"

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"
      loop:
        - "{{ docker_data_dir }}"
        - "{{ backup_dir_path }}"

  roles:
    # Installed required packages for local development
    - role: mirceanton.terraform
    - role: mirceanton.packer
    - role: mirceanton.ansible

    # Install docker to host services
    - role: mirceanton.docker

    - role: mirceanton.anacron

  tasks: []