# ===============================================
# ISO CONFIGURATION
# ===============================================
opnsense_iso_url: https://mirror.dns-root.de/opnsense/releases/22.7/OPNsense-22.7-OpenSSL-dvd-amd64.iso.bz2
opnsense_iso_name: OPNsense-22.7.iso
# ===============================================
# VM TEMPLATE CONFIGURATION
# ===============================================
#
# [Required] The name of the node on which to deploy the VM
opnsense_tpl_node: '{{ ansible_hostname }}'
#
# [Optional] The ID of the VM template
opnsense_tpl_id: 1100
#
# [Optional] The name of the VM template
opnsense_tpl_name: opnSense-tpl
#
# [Required] The path to the ISO file, including the storage device
opnsense_tpl_iso: local:iso/{{ opnsense_iso_name }}
#
# [Required] The password to set for the root user
opnsense_tpl_root_pass: ENC[AES256_GCM,data:XaOywcNkxQ==,iv:wIVVhRxoxVPjsA165syAAzmDY6thb4v+tX7p43KmWFs=,tag:aNqQyTMOYvAu3H8DDAF4Sg==,type:str]
#
# [Required] List of network devices
opnsense_tpl_networks:
    #
    # [Required] The name of the network bridge to attach to. (vmbr0, vmbr1 etc)
    - bridge: vmbr1
    #
    # [Required] The name of the network bridge to attach to. (vmbr0, vmbr1 etc)
    - bridge: vmbr0
#
# [Required] List of disks to assign to the VM
opnsense_tpl_disks:
    #
    # [Required] The name of the storage pool on which to store the disk
    - size: 16G
      #
      # [Required] The name of the storage pool on which to store the disk
      storage_pool: local-zfs
      #
      # [Required] The type of the storage pool on which to store the disk
      storage_pool_type: zfspool
#
# ===============================================
# VIRTUAL MACHINE CONFIGURATION
# ===============================================
#
# [Optional] The name of the VM
opnsense_vm_name: opnSense
#
# [Optional] The name of the VM
opnsense_vm_clone: '{{ opnsense_tpl_name }}'
#
# [Required] The name of the node on which to deploy the VM
opnsense_vm_target_node: '{{ ansible_hostname }}'
#
# [Optional] The ID of the VM
opnsense_vm_id: 100
#
# [Required] List of disks to assign to the VM
opnsense_vm_disks:
    #
    # [Required] The name of the storage pool on which to store the disk.
    - storage: local-zfs
      #
      # [Required] The size of the created disk.
      size: 16G
#
# [Required] List of network devices
opnsense_vm_networks:
    #
    # [Required] The name of the network bridge to attach to. (vmbr0, vmbr1 etc)
    - bridge: vmbr1
    #
    # [Required] The name of the network bridge to attach to. (vmbr0, vmbr1 etc)
    - bridge: vmbr0
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh6wns2rxpm6d6czfv25n293deew86kvvt848q00f4emvcllxqfqllqs9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTW5OTGk3WEoyM3FHdGdY
            UjVZRmQwaU41NWFnc3lsZGhUYVA2VkVSeXlNClpoQ3Nnb25Qb2JtVEpuSzZaRytw
            WVBsQVBqeDlSalFRUVlpejArekpDMGsKLS0tIFVYcUQzbVNZajZ0RXl3Ly9uWVNy
            cDlJMEFyK1NYQVVzVUdNNStFQXBPMmsKOm89YjbX4UknZPe9UGJ1i0X19y+ZoMnT
            VJ6ut4D1Q3G2CLsOnXPp8Hu3DD9SzRxkcyYQe4xEx7G+qHwO7INATg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-06T21:02:35Z"
    mac: ENC[AES256_GCM,data:l2o/HfrMECAZPNrFLL/cnAKsZWr7eShfb9s3533Yv30jt8uP1RAak0R+rDFiOUqPwshqjrPo1w9dSdOF7ODPmKCN3l91Yodd9Zy/gk51d4Fq1adjkwfz+sJ2xZ1kyY9GfuzEmqZid2fFEG8r0I5yUpIhLMpoUX/H+oeAe529pLc=,iv:2bO8qbXd/j3Vgpa5R12rY1UB/Lv43LQWPa8BAeazINY=,tag:BSKFmoT36DXwk1qdZgYbJQ==,type:str]
    pgp: []
    encrypted_regex: (ansible_host|ansible_user|pass|token)
    version: 3.7.3
