---
ansible_connection: local

hostname: automaton
domain: local
fqdn: "{{ hostname }}.{{ domain }}"

# ===============================================
# Deployment Configuration
# ===============================================
apt_utility_state: present
apt_utility_packages:
  - tree
  - curl
  - wget
  - unzip
  - htop
  - net-tools
  - nload
  - git
  - vim

# ===============================================
# Docker Swarm configuration
# ===============================================
docker_swarm_state: present
docker_swarm_iface: ens0

docker_proxy_network: traefik-net
docker_data_dir: /opt/docker
