---
# ===============================================
# ANSIBLE CONFIGURATION
# ===============================================
ansible_connection: local

# ===============================================
# HOST CONFIGURATION
# ===============================================
hostname: automaton
domain: local
fqdn: "{{ hostname }}.{{ domain }}"

# ===============================================
# DOCKER SWARM CONFIGURATION
# ===============================================
docker_swarm_state: present
docker_swarm_iface: ens0

docker_proxy_network: traefik-net
docker_data_dir: /opt/docker

vault_root_token: test1234
minio_root_user: root
minio_root_pass: test1234
gitlab_root_password: test1234
gitlab_runners_token: test1234