---
ansible_connection: local

# ===============================================
# Deployment Configuration
# ===============================================
apt_utility_state: present
apt_utility_packages:
  - tree
  - curl
  - wget
  - unzip
  - htop
  - net-tools
  - nload
  - git
  - vim
