---
# ===============================================
# ANSIBLE CONFIGURATION
# ===============================================
ansible_connection: local

# ===============================================
# HOST CONFIGURATION
# ===============================================
hostname: automaton
domain: local
fqdn: "{{ hostname }}.{{ domain }}"

# ===============================================
# DOCKER SWARM CONFIGURATION
# ===============================================
docker_swarm_state: present
docker_swarm_iface: ens0

docker_proxy_network: traefik-net

# ===============================================
# TRAEFIK CONFIGURATION
# ===============================================
traefik_stack_name: traefik
traefik_stack_data_dir_path: /opt/services/traefik
traefik_stack_data_dir_mode: u=rwx,g=rx,o=rx
traefik_stack_additional_dirs:
  - path: letsencrypt
    mode: u=rwx,g=rw,o=r
traefik_stack_template_files:
  - src: "{{ playbook_dir }}/templates/traefik/docker-compose.yml.j2"
    dest: docker-compose.yml
    mode: "u=r,g=r,o=r"
  - src: "{{ playbook_dir }}/templates/traefik/config.yml.j2"
    dest: config.yml
    mode: "u=r,g=r,o=r"
