---
# ===============================================
# ANSIBLE CONFIGURATION
# ===============================================
ansible_connection: local

# ===============================================
# HOST CONFIGURATION
# ===============================================
hostname: automaton
domain: local
fqdn: "{{ hostname }}.{{ domain }}"

# ===============================================
# DOCKER SWARM CONFIGURATION
# ===============================================
docker_swarm_state: present
docker_swarm_iface: ens0

docker_proxy_network: traefik-net

docker_healthcheck_interval: 5s
docker_healtcheck_timeout: 5s
docker_healthcheck_retries: 20

# ===============================================
# TRAEFIK CONFIGURATION
# ===============================================
traefik_stack_name: traefik
traefik_stack_data_dir_path: /opt/services/traefik
traefik_stack_data_dir_mode: u=rwx,g=rx,o=rx
traefik_stack_additional_dirs:
  - path: letsencrypt
    mode: u=rwx,g=rw,o=r
traefik_stack_template_files:
  - src: "{{ playbook_dir }}/templates/traefik/docker-compose.yml.j2"
    dest: docker-compose.yml
    mode: "u=r,g=r,o=r"
  - src: "{{ playbook_dir }}/templates/traefik/config.yml.j2"
    dest: config.yml
    mode: "u=r,g=r,o=r"

# ===============================================
# PORTAINER CONFIGURATION
# ===============================================
portainer_stack_name: portainer
portainer_stack_data_dir_path: /opt/services/portainer
portainer_stack_data_dir_mode: u=rwx,g=rx,o=rx
portainer_stack_additional_dirs:
  - path: data
    mode: u=rwx,g=rw,o=r
portainer_stack_template_files:
  - src: "{{ playbook_dir }}/templates/portainer/docker-compose.yml.j2"
    dest: docker-compose.yml
    mode: "u=r,g=r,o=r"

# ===============================================
# VAULT CONFIGURATION
# ===============================================
vault_stack_name: vault
vault_stack_data_dir_path: /opt/services/vault
vault_stack_data_dir_mode: u=rwx,g=rx,o=rx
vault_stack_additional_dirs:
  - path: data
    mode: u=rwx,g=rw,o=r
  - path: config
    mode: u=rwx,g=rw,o=r
vault_stack_template_files:
  - src: "{{ playbook_dir }}/templates/vault/docker-compose.yml.j2"
    dest: docker-compose.yml
    mode: "u=r,g=r,o=r"
  - src: "{{ playbook_dir }}/templates/vault/config.json.j2"
    dest: config/vault.json
    mode: "u=r,g=r,o=r"

# ===============================================
# MINIO CONFIGURATION
# ===============================================
minio_stack_name: minio
minio_stack_data_dir_path: /opt/services/minio
minio_stack_data_dir_mode: u=rwx,g=rx,o=rx
minio_stack_additional_dirs:
  - path: data
    mode: u=rwx,g=rw,o=r
minio_stack_template_files:
  - src: "{{ playbook_dir }}/templates/minio/docker-compose.yml.j2"
    dest: docker-compose.yml
    mode: "u=r,g=r,o=r"

minio_root_user: root
minio_root_pass: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname) }}"

# ===============================================
# JENKINS CONFIGURATION
# ===============================================
jenkins_stack_name: jenkins
jenkins_stack_data_dir_path: /opt/services/jenkins
jenkins_stack_data_dir_mode: u=rwx,g=rx,o=rx
jenkins_stack_additional_dirs:
  - path: data
    mode: u=rwx,g=rwx,o=rwx
jenkins_stack_template_files:
  - src: "{{ playbook_dir }}/templates/jenkins/docker-compose.yml.j2"
    dest: docker-compose.yml
    mode: "u=r,g=r,o=r"
